"""initial

Revision ID: 488561e8eae2
Revises: 
Create Date: 2021-06-27 18:43:38.531588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488561e8eae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
