"""empty message

Revision ID: 4ec52e8cb55c
Revises: 99f15877671c
Create Date: 2021-06-27 19:14:57.362128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ec52e8cb55c'
down_revision = '99f15877671c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cash', sa.Integer(), nullable=True))
    op.drop_column('user', 'cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cache', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'cash')
    # ### end Alembic commands ###
