"""empty message

Revision ID: 5bcef44981f7
Revises: 6000ac741391
Create Date: 2021-06-27 22:30:41.004467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcef44981f7'
down_revision = '6000ac741391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_data', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_data', 'time')
    # ### end Alembic commands ###
