"""empty message

Revision ID: 6000ac741391
Revises: d9b68d9b7276
Create Date: 2021-06-27 22:29:39.369682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6000ac741391'
down_revision = 'd9b68d9b7276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_data', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_data', sa.Column('time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
