"""empty message

Revision ID: 99f15877671c
Revises: 922f6ce04f49
Create Date: 2021-06-27 19:01:48.736881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f15877671c'
down_revision = '922f6ce04f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cache', sa.Integer(), nullable=True))
    op.drop_column('user', 'money')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'cache')
    # ### end Alembic commands ###
